### ISSUE TITLE
InDiaryManageActivity 변경

### ISSUE THREAD

**Issue by kyuwankim** [tokijh/Record#111]
1. activity_indiary_write_detail 삭제 및 activity_in_diary_manage로 통합
2. activity_in_diary_manage 내 Content 부분을 RecyclerView로 변경
3. RecyclerView를 표시할 item을 생성

**Comment by kyuwankim** [comment]
@tokijh InDiary xml에서 recyclerview 를 쓸라구 받았더니

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.0) from [com.android.support:design:25.3.0] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

이런 오류가 뜨는데

걍 바꿔주면 되겠지? 버전안맞는단거같은데

**Comment by tokijh** [comment]
@kyuwankim 뭐 AndroidStudio에서 업데이트 한거 있어요?

**Comment by tokijh** [comment]
@kyuwankim 그냥 fix되는거면 fix해서 해요

**Comment by kyuwankim** [comment]
ㄴㄴ 그런건 딱히 없고 gradle에서 recyclerview 버전을 25.3.1 에서 25.3.0 으루 바꾸니까 바로돼

**Comment by tokijh** [comment]
@kyuwankim 
저 아예 그런 내용없는데..?
```
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.android.gms:play-services:10.2.1'
    compile 'com.google.android.gms:play-services-auth:10.2.1'
    compile 'com.google.android.gms:play-services-maps:10.2.1'
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:design:25.3.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.facebook.android:facebook-android-sdk:4.20.0'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
```

**Comment by kyuwankim** [comment]
아 지금 내가 브랜치 판거에서 리사이클러뷰를 받은거라 올리진않아써

**Comment by tokijh** [comment]
@kyuwankim 그거 없으면 build에러 떠요?

**Comment by kyuwankim** [comment]
compile 'com.android.support:recyclerview-v7:25.3.0'
 하면 애러안떠

**Comment by tokijh** [comment]
@kyuwankim 그럼 저 버전으로 하는게 맞아요`'com.android.support:appcompat-v7:25.3.0'` 이게 저 버전이니깐요

**Comment by kyuwankim** [comment]
왜 다운로드를 받았는데 25.3.1을 줘서 설레게했던걸까.. 구글색기들..

**Comment by tokijh** [comment]
@kyuwankim 프로젝트 진행중에 저게 업데이트가 나왔더라고요 근데 함부로 업데이트를 못한게 혹시나 동작하지 않을까봐 안했어요

**Comment by kyuwankim** [comment]
굳

**Comment by kyuwankim** [comment]
@tokijh RecyclerView도 세로가 아니라 가로로 전시가 가능해?

**Comment by tokijh** [comment]
@kyuwankim 가능하죠

**Comment by kyuwankim** [comment]
@tokijh Orientation 해서?

**Comment by tokijh** [comment]
@kyuwankim 그죠?

**Comment by kyuwankim** [comment]
layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);

아하

**Comment by kyuwankim** [comment]
사진하고 내용 넣는부분을 만들었는데 상당히 구..구리다..

**Comment by kyuwankim** [comment]
일단 다 붙여서 올릴게

**Comment by tokijh** [comment]
@kyuwankim 제가 커멘트로 달아놓은것들은 해주시고 그냥 알려주시면 되요

**Comment by kyuwankim** [comment]
뭔가 액티비티를 바꾸고 item을 만들고 리사이클러뷰를 넣긴 했는데 뭔가 심히 잘못된단걸 느끼고있다.....ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kyuwankim** [comment]
리사이클러뷰에서 가져올 데이터가 없는데 띄우고싶을땐 어떻게해야돼??

**Comment by kyuwankim** [comment]
RecyclerView 상에서 item에 있는 imageView를 누르면 Dialog로 camera or gallery 를 제공하려고하는데 

>    protected void onActivityResult(int requestCode, int resultCode, Intent data) 
이 메소드를 통해서 imageview에 이미지를 넣었는데 리사이클러뷰 상에서는 아예 불러지지않음

어댑터에 데이터를 넣어야할거같은데 
Model 에 InDiary 클래스가 있는거같은데 여기에서 내용을 담을수있는 변수가 뭐인지 모르겠음...ㅠㅠ

내가 많이 부족하여 미안하다 .. 고기먹자...
뭐했다고 다섯시여 아우ㅠㅠㅠㅠㅠㅠㅠ

**Comment by tokijh** [comment]
@kyuwankim 지금 inDiary에 content없을걸요? RecyclerViewAdapter에서 직접 넣는게 아니라 Adpater에 Add하는식으로 해야할거같아요
