### ISSUE TITLE
Connect to Facebook

### ISSUE THREAD

**Issue by kyuwankim** [tokijh/Record#15]
Facebook 소셜 로그인 xml을 추가하고 기본 기능을 연결합니다

**Comment by tokijh** [comment]
push 할때 그냥 고대로 push해주세요 제가 실수로 issue_15 branch를 삭제해버렸네요...;;

**Comment by kyuwankim** [comment]
그냥 바로 푸시하면됨??

**Comment by tokijh** [comment]
푸시하면 다시 연결될거에요

**Comment by kyuwankim** [comment]
지금 PullRequest 했으니까 한번 봐줘

**Comment by tokijh** [comment]
네 보고있어요
