### ISSUE TITLE
Connect to googleLogin

### ISSUE THREAD

**Issue by kyuwankim** [tokijh/Record#27]
SigninActivity에 GoogleLogin을 추가하고 어플리케이션과 연결합니다

https://firebase.google.com/docs/auth/android/google-signin?hl=ko

**Comment by kyuwankim** [comment]
@timejp 구글연동은 파이어베이스로 하나벼 요거 연결하고 어제말한 검색이랑 아이템 만들게

**Comment by tokijh** [comment]
아 구글 firebase밖에 없어요?? firebase로 인증할거면 facebook도 통합시키는게 좋은데

**Comment by kyuwankim** [comment]
지금 설명은 그런식으로 나오는데 다른게 있나 한번 보고 알려줄게

**Comment by tokijh** [comment]
http://m.blog.naver.com/tkddlf4209/220723503941 이걸로 하면 firebase안써도 될거같아요

**Comment by kyuwankim** [comment]
https://developers.google.com/identity/sign-in/android/start 찾았다

**Comment by kyuwankim** [comment]
검색하자마자 위에꺼가 파이어베이스길레 난 또 통합된줄알았네

**Comment by kyuwankim** [comment]
아.. 나랑 같은거봤어.. 찌찌뽕

**Comment by tokijh** [comment]
똑같은거네요 ㅋㅋㅋㅋ
그리고 저거 계정하는건 형껄로 해줄수있나요?
제 계정으로는 생성할수있는 프로젝트 수 를 넘었다고 떠서,...

**Comment by kyuwankim** [comment]
ㅇㅋㅇㅋ 내가 해보겠슴다~

**Comment by tokijh** [comment]
감사합니다 ㅎㅎㅎ

**Comment by kyuwankim** [comment]
@timejp 일단 구글 버튼 달아놓고 팝업으로 구글로그인 연결되게는 해놨는데 이게 로딩도 느리고 로그인 후 처리가 또 없어서 일단 연결한거까지만 커밋해두어씀요

**Comment by tokijh** [comment]
@kyuwankim 커밋은 했는데 push는 안한거같네요 ㅋㅋㅋㅋ 이것도 callback함수가 있을거에요 아마...

**Comment by tokijh** [comment]
@kyuwankim 아 되어있네요 확인해볼게요

**Comment by kyuwankim** [comment]
그 maps를 최신버전으로 맞추면 
Auth 같은게 빨갛게떠버리더라구 

구글 공식사이트 가이드 따라하면 오류가나더라고... 핳

**Comment by tokijh** [comment]
@kyuwankim 일단 기능 구현 되었고요 소스 한번 확인해 보고 질문이나 이상한거 없으면 MR해주세요
