### ISSUE TITLE
Add Diary writeDetail, Add Indiary writeDetail 구성

### ISSUE THREAD

**Issue by kyuwankim** [tokijh/Record#52]
1. Floating Action Button group에 있는 각 item 클릭 시 Toast로 메세지가 나타나게 연결
 > Fab 통해서 사진아이템을 누르게되면 1)이전 사진 가지고오기 2)바로 찍어서 올리기 분기가 일어남
  fab:menu_openDirection="up" 통해서 item 내에서 다시 분기가 가능한가 봤지만
  fab:menu_openDirection="up" 이 속성은 그냥 그룹이 눌렸을때 방향이 위->아래 인가 아래 -> 방향으로 
  전시되는가의 차이
 > Fab group 안에 group을 이중으로 넣는 경우 : 오류가 화산처럼 터짐  
 > 일단은 앨범에서 가져오기 item을 하나 추가하는것이 가장 맞는 대안일듯 
2. date부분을 클릭시 DatePicker Dialog를 전시 후 설정된 날자를 set

* 가능하다면 Fab icon을 더 이쁜걸 찾아 바꾸고싶..다

@timejp 뭔가 내가 이슈를 막 닫고 merge를 해버린거같아불안해...

**Comment by tokijh** [comment]
@kyuwankim 그냥 해요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
